# Generated by Django 5.2.17 on 2026-09-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, upload_to='skills'),
        ),
    ]
